#!/bin/bash

##################################
# Author: Ibrahim Osama with the help of Abhishek.Veeramalla https://www.youtube.com/@AbhishekVeeramalla
#
# Date: 18/03/2023
#
# This script reports AWS resource usage
#
# Version: v1
####################################

# list S3 buckets
echo "Print list of S3 buckets"
aws s3 ls > output.txt

# list EC2 instances
echo "Print list of EC2 instances"
#aws ec2 describe-instances | jq '.Reservations[].Instances[].InstanceId' --> this is just in case you need a specific part of the output
aws ec2 describe-instances >> output.txt

# list lambda
echo "Print list of Lambda functions"
aws lambda list-functions >> output.txt

# list IAM users
echo "Print list of IAM users"
aws iam list-users >> output.txt
